version: '1.0'

services:
  web:
    image: 'bunny-web:latest'
    container_name: bunny_web
    ports:
      - '3000:3000'
    environment:
      - SERVER_PORT=3000
      - API_VERSION=${API_VERSION}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_USER=${CACHE_USER}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - S3_RECORD_FOLDER=${S3_RECORD_FOLDER}
      - S3_USER_IMAGE_FOLDER=${S3_USER_IMAGE_FOLDER}
      - S3_BATTLE_FOLDER=${S3_BATTLE_FOLDER}
      - AWS_DISTRIBUTION_NAME=${AWS_DISTRIBUTION_NAME}
      - DEFAULT_TEMPLATE_FILE=${DEFAULT_TEMPLATE_FILE}
    depends_on:
      - mysql
      - redis
  redis:
    image: 'bunny-redis:latest'
    container_name: bunny_redis
    ports:
      - '6379:6379'
  mysql:
    image: 'bunny-mysql:latest'
    container_name: bunny_mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  nginx:
    image: 'bunny-nginx:latest'
    container_name: bunny_nginx
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - ${pwd}/nginx/certificate_final.crt:${CERTIFICATE_KEY}
      - ${pwd}/nginx/private.key:${PRIVATE_KEY}

networks:
  default:
    driver: bridge