name: build and deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  connect-ec2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST_NAME: ${{ secrets.AWS_HOST_NAME  }}
          AWS_USER_NAME: ${{ secrets.AWS_USER_NAME  }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
      - name: SSH to ec2 host
        run: |
          echo ${{ AWS_PRIVATE_KEY }} > private_key && chmod 600 private_key
          echo ${{ TARGET_DIR }}
          ssh -o StrictHostKeyChecking=no -i private_key ${{ AWS_USER_NAME }}@${{ AWS_HOST_NAME }} '
  deploy-ec2:
    runs-on: ubuntu-22.04
    needs: connect-ec2
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: git pull
        run: |
          cd ${{ TARGET_DIR }} &&
          pwd &&
          git checkout ${{ steps.extract_branch.outputs.branch }} &&
          git pull origin ${{ steps.extract_branch.outputs.branch }} &&
          npm install
          pm2 restart socket
          '
